// Static schema for the "Theme reference" Settings tab. Each row carries
// both Twig and PHP forms so the screen can flip between them without
// regenerating data. Hand-maintained — keep in sync with docs/templates.md
// and the route dispatch in public/index.php.

export const ROUTES = [
  {
    type: 'post',
    templates: { twig: 'post.twig', php: 'post.php' },
    match: '/<folder>/<slug> — any folder except `pages`',
    vars: [
      { name: 'meta', type: 'array',
        twig: '{{ meta.title }}',
        php:  '<?= e($meta["title"]) ?>',
        desc: 'Front-matter merged with the index row — front-matter keys plus path, folder, slug, draft, mtime, taxonomy assignments.' },
      { name: 'html', type: 'html',
        twig: '{{ html|raw }}',
        php:  '<?= $html ?>',
        desc: 'Rendered Markdown body. Output raw — already sanitised.' },
    ],
  },
  {
    type: 'page',
    templates: { twig: 'page.twig', php: 'page.php' },
    match: '/<slug> — anything under `site/content/pages/`',
    vars: [
      { name: 'meta', type: 'array',
        twig: '{{ meta.title }}',
        php:  '<?= e($meta["title"]) ?>',
        desc: 'Same shape as post.meta.' },
      { name: 'html', type: 'html',
        twig: '{{ html|raw }}',
        php:  '<?= $html ?>',
        desc: 'Rendered Markdown body.' },
    ],
  },
  {
    type: 'archive',
    templates: { twig: 'archive.twig', php: 'archive.php' },
    match: '/<folder> — folder listings (paginated)',
    vars: [
      { name: 'folder', type: 'string',
        twig: '{{ folder }}',
        php:  '<?= e($folder) ?>',
        desc: 'Folder slug, e.g. "blog".' },
      { name: 'posts', type: 'list',
        twig: '{% for post in posts %}{{ post.title }}{% endfor %}',
        php:  '<?php foreach ($posts as $post): ?><?= e($post["title"]) ?><?php endforeach; ?>',
        desc: 'Array of post rows for this page of results. Each row is the same shape as `meta` on a single post.' },
      { name: 'intro', type: 'array | null',
        twig: '{% if intro and intro.html %}{{ intro.html|raw }}{% endif %}',
        php:  '<?php if (!empty($intro["html"])): ?><?= $intro["html"] ?><?php endif; ?>',
        desc: 'Optional intro content from `_index.md` in the folder (has `meta` + `html` keys, or null).' },
      { name: 'page', type: 'int',
        twig: '{{ page }}',
        php:  '<?= (int)$page ?>',
        desc: 'Current page number (1-based).' },
      { name: 'total_pages', type: 'int',
        twig: '{{ total_pages }}',
        php:  '<?= (int)$total_pages ?>',
        desc: 'Total pages for this archive.' },
    ],
  },
  {
    type: 'taxonomy',
    templates: { twig: 'taxonomy.twig', php: 'taxonomy.php' },
    match: '/categories/<term> or /tags/<term> (and any custom taxonomy)',
    vars: [
      { name: 'taxonomy', type: 'string',
        twig: '{{ taxonomy }}',
        php:  '<?= e($taxonomy) ?>',
        desc: 'Taxonomy slug — e.g. "categories", "tags".' },
      { name: 'term', type: 'string',
        twig: '{{ term }}',
        php:  '<?= e($term) ?>',
        desc: 'Term slug from the URL.' },
      { name: 'label', type: 'string',
        twig: '{{ label }}',
        php:  '<?= e($label) ?>',
        desc: 'Human-friendly term label (matches original casing).' },
      { name: 'posts', type: 'list',
        twig: '{% for post in posts %}{{ post.title }}{% endfor %}',
        php:  '<?php foreach ($posts as $post): ?><?= e($post["title"]) ?><?php endforeach; ?>',
        desc: 'Posts tagged with this term — same row shape as the archive.' },
      { name: 'page', type: 'int',
        twig: '{{ page }}',
        php:  '<?= (int)$page ?>',
        desc: 'Current page (1-based).' },
      { name: 'total_pages', type: 'int',
        twig: '{{ total_pages }}',
        php:  '<?= (int)$total_pages ?>',
        desc: 'Total pages for this term.' },
    ],
  },
  {
    type: 'feed',
    templates: { twig: 'feed.twig', php: 'feed.php' },
    match: '/feed and /<folder>/feed — Atom XML',
    vars: [
      { name: 'title', type: 'string',
        twig: '{{ title }}',
        php:  '<?= e($title) ?>',
        desc: 'Feed title (defaults to site name).' },
      { name: 'feed_url', type: 'string',
        twig: '{{ feed_url }}',
        php:  '<?= e($feed_url) ?>',
        desc: 'Absolute URL of this feed.' },
      { name: 'site_url', type: 'string',
        twig: '{{ site_url }}',
        php:  '<?= e($site_url) ?>',
        desc: 'Absolute URL of the site root.' },
      { name: 'updated', type: 'int',
        twig: '{{ updated|date("c") }}',
        php:  '<?= e(date("c", (int)$updated)) ?>',
        desc: 'Unix timestamp of the most recent item.' },
      { name: 'items', type: 'list',
        twig: '{% for item in items %}{{ item.title }}{% endfor %}',
        php:  '<?php foreach ($items as $item): ?><?= e($item["title"]) ?><?php endforeach; ?>',
        desc: 'Each item: { title, absolute_url, mtime, date }.' },
    ],
  },
  {
    type: '404',
    templates: { twig: '404.twig', php: '404.php' },
    match: 'Anything that does not resolve',
    vars: [
      { name: 'url', type: 'string',
        twig: '{{ url }}',
        php:  '<?= e($url) ?>',
        desc: 'Original request URL that triggered the 404.' },
    ],
  },
];

// Front-matter keys the framework recognises on every page/post. Anything
// else is passed through verbatim — useful for custom theme conventions.
export const META_KEYS = [
  { name: 'title',       type: 'string', twig: '{{ meta.title }}',       php: '<?= e($meta["title"]) ?>',
    desc: 'Page title — used in <title>, archive lists, and feed entries.' },
  { name: 'date',        type: 'string', twig: '{{ meta.date }}',        php: '<?= e($meta["date"]) ?>',
    desc: 'YYYY-MM-DD or any PHP-parseable date string. Drives archive sort and `<time>` rendering.' },
  { name: 'draft',       type: 'bool',   twig: '{% if meta.draft %}…{% endif %}', php: '<?php if (!empty($meta["draft"])): ?>…<?php endif; ?>',
    desc: 'When true the page is excluded from public routes/archives. Editor toggles via the Status field.' },
  { name: 'template',    type: 'string', twig: '{{ meta.template }}',    php: '<?= e($meta["template"]) ?>',
    desc: 'Per-post template override — "longform" picks `longform.{twig|php}`. Editor writes this via the Template dropdown.' },
  { name: 'image',       type: 'string', twig: '{{ meta.image }}',       php: '<?= e($meta["image"]) ?>',
    desc: 'Featured-image URL. Edited via the sidebar; archive rows surface it as `post.image`.' },
  { name: 'description', type: 'string', twig: '{{ meta.description }}', php: '<?= e($meta["description"]) ?>',
    desc: '`<meta name="description">` content — the header partial picks it up.' },
  { name: 'canonical',   type: 'string', twig: '{{ meta.canonical }}',   php: '<?= e($meta["canonical"]) ?>',
    desc: '`<link rel="canonical">` URL.' },
  { name: 'path',        type: 'string', twig: '{{ meta.path }}',        php: '<?= e($meta["path"]) ?>',
    desc: 'Content-relative path without `.md`, e.g. `blog/hello-world`. Injected by the index.' },
  { name: 'folder',      type: 'string', twig: '{{ meta.folder }}',      php: '<?= e($meta["folder"]) ?>',
    desc: 'Top-level folder, e.g. `blog`. Index-injected.' },
  { name: 'slug',        type: 'string', twig: '{{ meta.slug }}',        php: '<?= e($meta["slug"]) ?>',
    desc: 'Last segment of the path. Index-injected.' },
  { name: 'mtime',       type: 'int',    twig: '{{ meta.mtime|date("Y-m-d") }}', php: '<?= e(date("Y-m-d", (int)$meta["mtime"])) ?>',
    desc: 'Unix mtime of the underlying `.md` file. Index-injected.' },
  { name: 'url',         type: 'string', twig: '{{ post.url }}',         php: '<?= e($post["url"]) ?>',
    desc: 'Public URL for the row, derived from the path. Present on archive rows.' },
];

export const HELPERS = [
  { name: 'e',         returns: 'string',
    twig: '{{ e(value) }}',
    php:  '<?= e($value) ?>',
    desc: 'HTML-escape via htmlspecialchars(ENT_QUOTES, UTF-8). Twig autoescapes; call manually only when escaping is off.' },
  { name: 'partial',   returns: 'void',
    twig: '{{ partial("header", { title: "Hi" }) }}',
    php:  '<?php partial("header", ["title" => "Hi"]); ?>',
    desc: 'Render a partial from the active theme. Resolves `components/<name>.{php,twig}` then legacy `_<name>` / `<name>` variants.' },
  { name: 'asset_url', returns: 'string',
    twig: '{{ asset_url("style.css") }}',
    php:  '<?= e(asset_url("style.css")) ?>',
    desc: "Prefix `/assets/` — the active theme's `assets/` is symlinked there." },
  { name: 'paginate',  returns: 'string (HTML)',
    twig: '{{ paginate(page, total_pages, "/blog")|raw }}',
    php:  '<?= paginate($page, $total_pages, "/blog") ?>',
    desc: 'Returns prev / "Page X of Y" / next nav block. Empty when total ≤ 1.' },
  { name: 'slug_url',  returns: 'string',
    twig: '{{ slug_url("PHP", "tags") }}',
    php:  '<?= e(slug_url("PHP", "tags")) ?>',
    desc: 'URL for a taxonomy term archive — e.g. /tags/php. Slugifies first.' },
  { name: 'inspect',   returns: 'string (HTML)',
    twig: '{{ inspect(meta, "meta")|raw }}',
    php:  '<?= inspect($meta, "meta") ?>',
    desc: 'Pretty-print any value as a collapsible labelled dump. Pairs with the Debug starter.' },
];

export const GLOBALS = [
  { name: 'posts',       returns: 'list',
    twig: '{% set recent = posts({ folder: "blog", limit: 5 }) %}',
    php:  '<?php $recent = posts(["folder" => "blog", "limit" => 5]); ?>',
    desc: 'Query the post index — filter, sort, paginate. See docs/templates.md.' },
  { name: 'render',     returns: 'void',
    twig: '— (Twig templates are rendered by render() from PHP; theme code rarely calls it directly.)',
    php:  '<?php render("post", ["meta" => $meta, "html" => $html]); ?>',
    desc: 'Render a named template — PHP wins, Twig fallback. Used by index.php to dispatch routes.' },
  { name: 'not_found',  returns: 'void',
    twig: '— (called from PHP side; not used directly in Twig templates.)',
    php:  '<?php not_found(); ?>',
    desc: "Send a 404 + render the active theme's 404 template." },
  { name: 'csrf_token', returns: 'string',
    twig: '{{ csrf_token() }}',
    php:  '<?= e(csrf_token()) ?>',
    desc: 'Current session CSRF token. Admin-only; useful for theme-side admin links.' },
  { name: 'config',     returns: 'array | object',
    twig: '{{ config.site.name }}',
    php:  '<?= e($config->get("site")["name"] ?? "") ?>',
    desc: "Twig sees `config` as a plain array; PHP sees the MD\\Config object — call `$config->get('key')`." },
];
